### ISSUE TITLE
Why depend on both `yaml-rust2` and `serde_yaml`?

### ISSUE THREAD

**Issue by Ecco** [yaml-schema/yaml-schema#1]
Thank you for this library! Wouldn't it make sense to use *either* `serde_yaml` *or* `yaml-rust2`, maybe offering the option with a feature flag? Otherwise anyone using this library will pull both dependencies.

**Comment by aisrael** [comment]
Hi, Ecco! Thanks for stopping by!

Initially, I did mean to do _all_ parsing using just `yaml-rust2`, as it's a bit lower level and I figured might be needed at some point to report more specific and detailed validation errors.

It's not quite there yet, though, so still just using `serde_yaml` as well for that part.

However, just for loading the YAML schema itself, which is relatively well-defined, `serde_yaml` does the trick.

Now, the thing is, since `serde_yaml` has been 'deprecated', I guess until a definitive fork pops up I'm also considering parsing the schema file itself using `yaml-rust2` as well.

WDYT?

**Comment by Ecco** [comment]
I think the main problem here is that anyone using your library will transitively inherit your dependencies as well, making their binary larger. I agree that the current situation of Rust and YAML is a bit messy with no _de facto_ standard. Have you looked at [saphyr-rs/saphyr](https://github.com/saphyr-rs/saphyr)? It's being written by the maintainers of `yaml-rust2` :)

**Comment by aisrael** [comment]
@Ecco I think you'd be glad to know that, after getting `serde_yaml` to parse the input into an intermediary model, then transforming that intermediary model into the actual schema model used for validation, I've started to use `saphyr` instead to directly construct the schema model from the `saphyr::Yaml` doc (saves a whole lot of code, and can do one-step ingest).

Afterwards, I plan to rewrite the validation to also use `saphyr_parse` directly so can perform validation as it goes without having to parse the entire document first.

**Comment by aisrael** [comment]
https://github.com/yaml-schema/yaml-schema/pull/6
